require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  # TODO: Explore which exact syntax version mruby is compatible with
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 80

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/**/*.rb'

Metrics/BlockNesting:
  Exclude:
    - 'test/sprintf.rb'

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'test/**/*.rb'

Security/Eval:
  Exclude:
    - 'test/**/*.rb'

Security/YAMLLoad:
  Exclude:
    - 'test/**/*.rb'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Exclude:
    - 'Rakefile'

Style/DoubleNegation:
  Enabled: false

Style/ExpandPathArguments:
  # __dir__ is not available in mruby
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/NumericPredicate:
  # Numeric#negative? is not available in mruby
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
