# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bundler',             '~> 2.2'
gem 'rake',                '~> 13.0'
gem 'rubocop',             '~> 1.25'
gem 'rubocop-performance', '~> 1.13'
gem 'rubocop-rake',        '~> 0.6'
