# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bundler',             '~> 2.3'
gem 'rake',                '~> 13.0'
gem 'rubocop',             '~> 1.40'
gem 'rubocop-performance', '~> 1.15'
gem 'rubocop-rake',        '~> 0.6'
