# frozen_string_literal: true

desc 'Run default checks'
task default: :lint

desc 'Run code analysis tools'
task lint: :rubocop

desc 'Fix code style (rubocop --auto-correct)'
task fix: 'rubocop:auto_correct'

begin
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
rescue LoadError
  nil
end
