require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 80

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/**/*_spec.rb'

RSpec/ContextWording:
  Prefixes:
    - 'and'
    - 'for'
    - 'using'
    - 'when'
    - 'with'
    - 'without'

RSpec/FilePath:
  CustomTransform:
    KernAux: kernaux

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Security/Eval:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Exclude:
    - 'Rakefile'

Style/DoubleNegation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/*/extconf.rb'

Style/HashAsLastArrayItem:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
