#!/bin/sh

set -e

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='x86_64'
HOST="$ARCH-elf"
PREFIX="$REPO/dest/dev-cross-$ARCH"
CROSS="$REPO/vendor/cross/root/bin/$HOST"

export     AR="$CROSS-ar"
export     CC="$CROSS-gcc"
export RANLIB="$CROSS-ranlib"

export CFLAGS='-ffreestanding -nostdlib -fno-stack-protector -mabi=sysv -mcmodel=kernel -mno-80387 -mno-red-zone'

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --disable-pic --with-libc
