#!/bin/sh

set -e

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='x86_64'
HOST="$ARCH-elf"
PREFIX="$REPO/dest/dev-cross-$ARCH"
CROSS="$REPO/vendor/cross/bin/$HOST"

export     AR="$CROSS-ar"
export     CC="$CROSS-gcc"
export RANLIB="$CROSS-ranlib"

export CFLAGS='-ffreestanding -nostdlib -fno-builtin -fno-stack-protector -fno-pic -mabi=sysv -mcmodel=kernel -mno-red-zone -mno-80387 -mno-3dnow -mno-sse -mno-sse2'

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --with-libc
