#!/bin/sh

set -eux

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

PREFIX="$REPO/dest/dev-native"

"$REPO/configure" --prefix="$PREFIX" --enable-checks-all
