#!/bin/sh

set -eux

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='i386'
HOST="$ARCH-elf"
TARGET='i686-linux-gnu'
PREFIX="/opt/libkernaux/$ARCH"

export     AR="$TARGET-ar"
export     CC="$TARGET-gcc"
export RANLIB="$TARGET-ranlib"

export CFLAGS='-ffreestanding -nostdlib -fno-stack-protector'

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --disable-pic --with-libc
