#!/bin/sh

set -eux

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='riscv64'
HOST="$ARCH-elf"
TARGET='riscv64-linux-gnu'
PREFIX="/opt/tailix/libkernaux/$ARCH"

export     AR="$TARGET-ar"
export     CC="$TARGET-gcc"
export RANLIB="$TARGET-ranlib"

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --enable-freestanding --with-libc
