#!/bin/sh

set -eux

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='x86_64'
HOST="$ARCH-elf"
TARGET='x86_64-linux-gnu'
PREFIX="/opt/tailix/libkernaux/$ARCH"

export     AR="$TARGET-ar"
export     CC="$TARGET-gcc"
export RANLIB="$TARGET-ranlib"

export CFLAGS='-mabi=sysv -mcmodel=kernel -mno-80387 -mno-red-zone'

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --enable-freestanding --with-libc
