#!/bin/sh

set -e

REPO="$(realpath "$(dirname "$(realpath "$0")")/..")"
if [ -f "$REPO/Makefile" ]; then make -C "$REPO" distclean; fi

ARCH='x86_64'
HOST="$ARCH-elf"
TARGET='x86_64-linux-gnu'
PREFIX="/opt/libkernaux/$ARCH"

export     AR="$TARGET-ar"
export     CC="$TARGET-gcc"
export RANLIB="$TARGET-ranlib"

export CFLAGS='-ffreestanding -nostdlib -fno-builtin -fno-stack-protector -mabi=sysv -mcmodel=kernel -mno-80387 -mno-red-zone'

"$REPO/configure" --host="$HOST" --prefix="$PREFIX" --disable-pic --with-libc
