#!/bin/sh

set -e

ARCH='x86_64'
HOST="$ARCH-elf"
REPO="$(pwd)"
PREFIX="$REPO/vendor/cross"
BIN="$PREFIX/bin"

export     AR="$BIN/$HOST-ar"
export     CC="$BIN/$HOST-gcc"
export RANLIB="$BIN/$HOST-ranlib"

export CFLAGS='-ffreestanding -nostdlib -fno-builtin -fno-stack-protector'

./configure --host="$HOST" --enable-assert --enable-guard --with-libc
