[package]
name = "kernaux"
version = "0.2.0"
authors = ["Alex Kotov <kotovalexarian@gmail.com>"]
edition = "2021"
description = "Safe binding to libkernaux - auxiliary library for kernel development"
readme = true
homepage = "https://github.com/tailix/libkernaux/tree/master/pkgs/rust"
repository = "https://github.com/tailix/libkernaux/tree/master/pkgs/rust"
license = "MIT"
keywords = ["ffi", "embedded", "bindings"]
categories = ["api-bindings", "embedded", "parsing"]
publish = true

[dependencies]
kernaux-sys = "0.0.0"
