name: Full kernels

jobs:
  default:
    runs-on: ubuntu-latest
    env:
      CROSS_COMPILE: 'riscv64-linux-gnu-'
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: sudo apt-get --yes install crossbuild-essential-riscv64
      - working-directory: vendor/u-boot
        name: U-Boot defconfig
        run: make qemu-riscv64_smode_defconfig
      - working-directory: vendor/u-boot
        name: U-Boot make
        run: make
      - working-directory: vendor/opensbi
        name: OpenSBI
        run: make PLATFORM=generic FW_PAYLOAD_PATH=../u-boot/u-boot.bin
