name: Tester for Stivale 2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies
        run: sudo apt-get --yes install crossbuild-essential-i386
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure --host='x86_64-elf' --enable-freestanding --with-libc-all --with-tester-stivale2 AR="$(which x86_64-linux-gnu-gcc)" CC="$(which x86_64-linux-gnu-gcc)" RANLIB="$(which x86_64-linux-gnu-ranlib)" CFLAGS='-mabi=sysv -mcmodel=kernel -mno-80387 -mno-red-zone'
      - name: make
        run: make
